### ISSUE TITLE
vglrun Rhel 7.5 GDM

### ISSUE THREAD

**Issue by red-erik** [VirtualGL/virtualgl#100]
Hello,
I'm really new to all this stuff, so forgive if the question is silly but I didn't find an explanation.
I have a lot of Rhel  6.x and 7.x servers and, on some (the most important) 7.5 servers I'm not able to have vglrun working. The only difference is that on those servers the $DISPLAY variable is populated with the IP address of the server and not the hostname or localhost (so the if ..then always fails).
We modified the vglrun script with an if checking for "hostname -i" too and that way it works, but we can't understand what is causing the problem.
Nothing strange in xorg.conf or gdm.conf
Thank you very much for any suggestions or hints.

Red.

**Comment by dcommander** [comment]
Before I can determine how best to address this, I need to understand why `DISPLAY` is being populated with the IP address.  That should never happen on RHEL by default, so something must be explicitly setting that environment variable.  Otherwise, `DISPLAY` should always be of the form `:{n}.{s}` (where `{n}` is the display number and `{s}` is the default screen) when using an X proxy session (including TurboVNC) and of the form `localhost:{n}.0` when using SSH with X11 tunneling.  The reason why `DISPLAY` should never contain an IP address is that this forces the X application to use TCP in order to send requests to the X server.  If the X server is on the same machine, then TCP introduces additional overhead (relative to Unix domain sockets.)  If the X server is on a different machine, then opening it up to TCP connections is a security risk.

How are you connecting to the VirtualGL server?  Are you using an X proxy?  `vglconnect`?

**Comment by red-erik** [comment]
Hello,
we use Cygwin (terminal), vglconnect (no proxy) and X11 is on the same host.

Red.

**Comment by dcommander** [comment]
What arguments are you passing to `vglconnect`, if any?  If you accidentally passed `-x` to it, then that would explain why `DISPLAY` contains an IP address.  Otherwise, using `vglconnect` normally should activate SSH X11 tunneling, so `DISPLAY` will be of the form `localhost:{n}.0`.  If it's not, then that points to a problem on the server.

**Comment by red-erik** [comment]
We don't pass any parameters. If I use -x than it works without modifying vglrun script. I'm convinced that the problem is on the server but I can't understand where it comes from.

**Comment by dcommander** [comment]
Is X11 tunneling enabled/allowed in /etc/ssh/sshd_config on the server?  If not, then that would explain the problem.  If everything is working properly with SSH, then `DISPLAY` should have an initial value of the form `localhost:{n}.0` even before you invoke vglrun.  If `DISPLAY` is empty, then vglrun assumes that SSH X11 tunneling is not being used, and it populates `DISPLAY` from `SSH_IP` (the IP address of the SSH client.)  vglrun outputs one of two messages to tell you what it's doing:

```
[VGL] NOTICE: Automatically setting the DISPLAY environment variable to
[VGL]    {foo}, based on the IP address of your SSH client.
```
or
```
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    {foo}, the IP address of your SSH client.
```
I'm guessing you're seeing the former message (always include any [VGL] messages in a VirtualGL bug report, BTW.)  You should be seeing the latter message.

**Comment by red-erik** [comment]
Hello,
on both working and not working servers we have (in sshd_config):
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTunnel no

**Comment by red-erik** [comment]
Not working output (original script vglrun renamed to vglrun_bck)
[root@xxxxxxxxx ~]# /opt/VirtualGL/bin/vglrun_bck /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Quadro P4000/PCIe/SSE2
[VGL] ERROR: Could not connect to VGL client.  Make sure that vglclient is
[VGL]    running and that either the DISPLAY or VGL_CLIENT environment
[VGL]    variable points to the machine on which vglclient is running.
[VGL] ERROR: in connect--
[VGL]    283: Connection refused
[root@xxxxxxx ~]# echo $DISPLAY
172.25.2.5:14.0

This is the IP address of the Linux server

**Comment by dcommander** [comment]
Weird.  OK, I guess maybe there is some setting that is causing the SSH server to set the `DISPLAY` variable differently.  I'll see if I can reproduce it.

**Comment by red-erik** [comment]
Hello,
do you have some news ? It seems that an all RHEL 7.x we have the same problem.
Regards.

Red.

**Comment by dcommander** [comment]
I use RHEL 7.x on a daily basis, so no, "all RHEL 7.x" do not have this problem.  I will investigate prior to the 2.6.2 release.  That's all I can promise.

**Comment by red-erik** [comment]
Ok, thank you very much for your support.

Red.

**Comment by dcommander** [comment]
The underlying cause was that `X11UseLocalhost` was set to `no` in sshd_config, which causes the `DISPLAY` environment variable to take the form of `{IP-address}:{n}.0` rather than `localhost:{n}.0`.  The only purpose of this is allowing the server end of the tunneled X11 connection to be shared with other hosts, which represents a security risk, so I do not recommend setting `X11UseLocalhost=no` unless you absolutely need to do so.  However, the commit I just pushed modifies `vglrun` so that it can properly handle `X11UseLocalhost=no`.  Please test the 2.6.x pre-release (https://virtualgl.org/DeveloperInfo/PreReleases) and confirm that it fixes the problem for you.

**Comment by red-erik** [comment]
Hello,
thank you for your support. On our hand, we discovered the difference on a working server and a not working one. It's related to IPv6 disabled setting.
From
https://www.linuxquestions.org/questions/linux-networking-3/x-forwarding-though-ssh-not-working-$display-not-set-879365/
Apparently, disabling ipv6 in any way messes with X forwarding in ssh, it turns out it's an openssh issue. The posts suggest two workarounds:
1. add '-4' to the options passed to sshd in /etc/default/ssh
2. add 'AddressFamily inet' in /etc/ssh/sshd_config
The second option worked well in our environment.
Regards.

Red.

**Comment by dcommander** [comment]
@red-erik if that is an effective workaround for this issue, then I'm going to revert d9eea40, because apparently that approach causes a regression on some platforms.

**Comment by red-erik** [comment]
Hello,
yes, do it. I confirm that  d9eea40 does not solve our issue.
Thank you very much.
Regards.
