### ISSUE TITLE
GPU memory leak with EGL backend in 3.0.x

### ISSUE THREAD

**Issue by tsondergaard** [VirtualGL/virtualgl#218]
The egl backend appears to leak content associated with close/destroyed windows/contexts causing a substantial amount of GPU memory to be used by unit tests that open and close a lot of windows. 

I have recorded [example2.trace](https://vitalimageseur-my.sharepoint.com/:u:/g/personal/tsondergaard_vitalimages_com/ESQp8Fuvlv9HqatpEhbxJlEBwFz241Si47FPzsdPyVCn8Q?e=2HdQcJ) with [apitrace](https://apitrace.github.io/). To replay the trace run the following commands:

```
# This step differs depending on distro.
dnf install apitrace

# Decompress the downloaded trace
unxz example2.trace.xz

# Run with :0 (GLX backend) - no substantial leaks
vglrun apitrace replay example2.trace

# Run with egl - substantial leaks
vglrun apitrace replay example2.trace

# Run with egl in debugger - substantial leaks
vglrun gdb --args apitrace replay example2.trace
```

I have just used nvidia-smi to watch the GPU memory usage as the program executes with `watch -n1 nvidia-smi` in a second terminal. The difference is very visible. You can use the debugger to make it more visible by breaking on exit.

It's very likely that the unit tests are doing bad/silly things, but since the GPU memory usage only balloons significantly with egl I thought it worth reporting.

I've reproduced this with 3.0.1 and with the head of 3.0.x (commit 8051ba1a2412).

**Comment by dcommander** [comment]
I can reproduce the issue, but it will take some time to debug.  I will need to figure out exactly what is triggering the problem at the low level.  You can accelerate that process by providing a simple OpenGL test application that replicates the problem.

**Comment by tsondergaard** [comment]
I'll see what I can do.

**Comment by tsondergaard** [comment]
I have a suspicion. My unit test and therefore the recorded apitrace does not explicitly free resources associated with an OpenGL context - instead the expectation is that when the context is destroyed all associated resources will be deleted. But with VGL_DISPLAY=egl PBuffers are emulated using RBOs. This comment from server/RBOContext.h explains that all contexts created by the application will be shared with the "RBO context":

```c++
		// The EGL back end emulates Pbuffers using RBOs, but RBOs are specific to
		// a particular OpenGL context, whereas Pbuffers are not.  Thus, the EGL
		// back end creates, as needed, a dedicated OpenGL context (the "RBO
		// context") and shares that context with any new unshared OpenGL contexts
		// that the 3D application asks to create or that the faker creates behind
		// the scenes.  The RBO context is used behind the scenes when creating,
		// destroying, or swapping a Pbuffer (either an application-requested
		// Pbuffer or a Pbuffer that the faker uses to emulate an OpenGL window),
		// operations that do not require an OpenGL context to be current.  Sharing
		// the RBO context with application-requested or faker-requested contexts
		// allows those contexts to be used for rendering into the RBOs, even
		// though those contexts were not current when the RBOs were created.
```

So that is why my test that runs without leaking when it is run without vgl our with vgl with GLX backend starts leaking like crazy with the egl backend.

I guess there is no way to fix this? It is only in our unit tests that we run into this problem, because we create and toss away a ton of OpenGL contexts.

**Comment by dcommander** [comment]
The RBO context is deleted in the body of `XCloseDisplay()`, but it sounds like it should also be deleted in the body of `glXDestroyContext()` if it is no longer in use.  I'll look into that.

**Comment by dcommander** [comment]
It would still be helpful to have a small test application that demonstrates the problem.

**Comment by dcommander** [comment]
Correction:

The purpose of the RBO context is to detach the lifespan of the RBO (which is emulating a GLX drawable) from the lifespan of the OpenGL context, so the RBO context should not be destroyed in the body of `glXDestroyContext()`.  However,  perhaps it should be destroyed (if unused) whenever the GLX drawable is destroyed.  The RBOs themselves are always destroyed along with the GLX drawable they are emulating, e.g. in the body of `glXDestroyPbuffer()` or `XDestroyWindow()` or `glXDestroyPixmap()`.  However, perhaps the underlying implementation doesn't really destroy them until the RBO context is destroyed.

Yet another reason why I need to see sample code, in order to understand where exactly the EGL back end behavior diverges from the GLX back end behavior.

**Comment by tsondergaard** [comment]
Here is a repro case - actually mostly written by chat-gpt :-)

```c++
#include <QApplication>
#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QOpenGLTexture>
#include <GL/gl.h>

class MyGLWidget : public QOpenGLWidget, protected QOpenGLFunctions
{
public:
    MyGLWidget()
    {
        setMinimumSize(600, 600);
    }

    ~MyGLWidget() override
    {
        if (!(qEnvironmentVariable("LEAK_TEXTURE", QLatin1String("0")) == QLatin1String("1"))) {
            delete m_texture;
        }
    }

protected:
    void initializeGL() override
    {
        initializeOpenGLFunctions();

        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);

        // Generate a checkerboard pattern for the texture
        QImage textureImage(1024, 1024, QImage::Format_ARGB32);
        for (int y = 0; y < textureImage.height(); ++y)
        {
            for (int x = 0; x < textureImage.width(); ++x)
            {
                int c = (((x & 0x20) == 0) ^ ((y & 0x20)  == 0)) * 255;
                textureImage.setPixel(x, y, qRgb(c, c, c));
            }
        }

        glEnable(GL_TEXTURE_2D);

        // Load the texture into OpenGL
        m_texture = new QOpenGLTexture(textureImage);
        m_texture->setMinificationFilter(QOpenGLTexture::Nearest);
        m_texture->setMagnificationFilter(QOpenGLTexture::Linear);
        m_texture->setWrapMode(QOpenGLTexture::Repeat);
    }

    void paintGL() override
    {
        glClear(GL_COLOR_BUFFER_BIT);

        // Draw the quad with the texture
        m_texture->bind();
        glBegin(GL_QUADS);
        glTexCoord2f(0.0f, 0.0f);
        glVertex2f(-1.0f, -1.0f);
        glTexCoord2f(1.0f, 0.0f);
        glVertex2f(1.0f, -1.0f);
        glTexCoord2f(1.0f, 1.0f);
        glVertex2f(1.0f, 1.0f);
        glTexCoord2f(0.0f, 1.0f);
        glVertex2f(-1.0f, 1.0);
        glEnd();
    }

    QOpenGLTexture *m_texture = nullptr;
};

int main(int argc, char **argv)
{
    QApplication app(argc, argv);

    while (true) {
        MyGLWidget w;
        w.show();
        app.exec();
    }
}
```

Build on Fedora Linux:
```
g++ -Wall -Wextra -g $(pkg-config --cflags --libs Qt5Core Qt5Gui Qt5Widgets) -lGL -o example example.cc
```



Run like below. When the window is closed a new one will pop up. Monitor GPU memory usage with e.g `nvidia-smi --loop 1`. Exit program with Ctrl+C in console.

```
# No GPU memory leaked, app cleans up itself:
LEAK_TEXTURE=0 /opt/easyviz/virtualgl/bin/vglrun -d :0 build/qtutility/src/sandbox2 

# No GPU memory leaked, driver cleans up when OpenGL context is destroyed:
LEAK_TEXTURE=1 /opt/easyviz/virtualgl/bin/vglrun -d :0 build/qtutility/src/sandbox2 

# GPU memory leaked, "RBO context" keeps texture from being destroyed with the applications context
LEAK_TEXTURE=1 /opt/easyviz/virtualgl/bin/vglrun -d egl build/qtutility/src/sandbox2 
```

I'd like to add that this is an edge case that probably wont bother most applications. We've only run into it in unit test suites where our test executables create a lot of temporary contexts and were not sufficiently diligent in cleaning up. I have solved the clean up problem in our application unit tests so this issue is not a huge concern for us.

Thanks for all the hard work you have put into VirtualGL. It is greatly appreciated.

**Comment by dcommander** [comment]
Thanks for the example application.  The EGL back end has, frankly, been a source of great frustration for me.  I unfortunately had to spend hundreds of uncompensated hours to finish it, because the funding I did manage to secure for it was contingent upon successfully completing the feature.  Because of the complexities of emulating Pbuffers using RBOs, completing the feature took a lot longer than anticipated.  The RBO context is at the heart of that complexity, and it is necessitated by the fact that RBOs are always tied to a context but GLX drawables are not.  To make matters worse, I cannot tie the RBO context to a GLX drawable (`FakePbuffer`) instance, because that instance might not exist at the time `glXCreateContext()` is called.  The EGL back end really needs a Pbuffer equivalent of the `EGL_multiview_window` extension.  Then I could jettison all of the Pbuffer emulation crap that is causing problems such as these.  I begged and pleaded for nVidia to implement such an extension, but unfortunately VirtualGL isn't a big enough player to get their attention. 

I need to look at it in more detail next week, but it might be possible to work around the issue by implementing context and drawable reference counts for the RBO context and destroying the RBO context when a GLX context or drawable is destroyed and both reference counts reach 0.  The example application ultimately calls `xcb_destroy_window()` to destroy the window and `glXDestroyContext()` to destroy the context, so that should trigger destruction of the RBO context.  I'm going to have to thoroughly test the resulting code, however, with Piglit and fakerut, to make sure it doesn't break anything.

**Comment by dcommander** [comment]
Should now be fixed in both the 3.1 and 3.0 stable branches and pre-release builds.  Please test.

**Comment by tsondergaard** [comment]
Thanks for jumping on this so quickly. I have tested 3.0.x (cc9543aaefb1) and it is unfortunately  broken with the example in https://github.com/VirtualGL/virtualgl/issues/218#issuecomment-1344762630. It fails after the first window is closed and it needs to open the next with the following error:
```
$ LEAK_TEXTURE=1 /home/ts/src/virtualgl/build/install/bin/vglrun -d egl ./example
[VGL] ERROR: OpenGL error 0x0502
[VGL] ERROR: in createBuffer--
[VGL]    154: Could not create FBO
```

**Comment by dcommander** [comment]
That's weird.  I can't reproduce any failure with the nVidia drivers, but I do observe a similar failure with my AMD GPU.  I'll investigate.

**Comment by dcommander** [comment]
Should be fixed now.  Look for today's date in the pre-release build page to indicate that the build has completed and contains the fix.

**Comment by tsondergaard** [comment]
Tested commit a577539ee3a092679d34b3788082eefa17c3f1b7 (HEAD -> 3.0.x, origin/3.0.x) crash is now fixed and it also fixes the leak in the repro example that I provided in https://github.com/VirtualGL/virtualgl/issues/218#issuecomment-1344762630. However, it does not fix the leak with VGL_DISPLAY=egl in my real program. This turns out to be because we use QtWebEngine and for this we call [QtWebEngine::initialize()](https://doc.qt.io/qt-5/qtwebengine.html#initialize) which has the effect of setting [Qt::AA_ShareOpenGLContexts](https://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum) to true. I have modified the repro with the patch and that brings the situation back to the original situation in https://github.com/VirtualGL/virtualgl/issues/218#issuecomment-1344762630. Everything stated in that comment but using the patched repro example remains true:

```diff
$ diff -u example_orig.cc example.cc 
--- example_orig.cc	2022-12-17 15:08:17.782903708 +0100
+++ example.cc	2022-12-17 15:05:52.419219304 +0100
@@ -69,6 +69,7 @@
 
 int main(int argc, char **argv)
 {
+    QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts, true);
     QApplication app(argc, argv);
 
     while (true) {
```

That means that it does not leak except with VGL_DISPLAY=egl.

I don't yet understand why it *doesn't* leak when not using virtualgl or with VGL_DISPLAY=:0, but I suppose there is a good change Qt is basically implementing the same trick as you have implemented in vgl, which means that the Qt shared context is holding the vgl RBO context alive and vice versa? I'll do a bit more testing to see if I can figure it out.

**Comment by tsondergaard** [comment]
No, Qt is doing something different to prevent leaking via shared contexts. Here is a diff that opens two windows that share contexts due to use of `Qt::AA_ShareOpenGLContexts`:

```diff
$ diff -u example_orig.cc example.cc 
--- example_orig.cc	2022-12-17 15:08:17.782903708 +0100
+++ example.cc	2022-12-17 15:25:18.364844892 +0100
@@ -69,11 +69,18 @@
 
 int main(int argc, char **argv)
 {
+    QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts, true);
     QApplication app(argc, argv);
 
+    MyGLWidget w_old;
+    w_old.show();
+    w_old.setWindowTitle("Old");
+
     while (true) {
-        MyGLWidget w;
-        w.show();
+        auto w = new MyGLWidget;
+        w->setAttribute(Qt::WA_DeleteOnClose, true);
+        w->show();
+        QObject::connect(w, &QObject::destroyed, [] { QCoreApplication::quit(); });
         app.exec();
     }
```

<details>
<summary>Click to see full updated example</summary>
```c++
#include <QApplication>
#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QOpenGLTexture>
#include <GL/gl.h>

class MyGLWidget : public QOpenGLWidget, protected QOpenGLFunctions
{
public:
    MyGLWidget()
    {
        setMinimumSize(600, 600);
    }

    ~MyGLWidget() override
    {
        if (!(qEnvironmentVariable("LEAK_TEXTURE", QLatin1String("0")) == QLatin1String("1"))) {
            delete m_texture;
        }
    }

protected:
    void initializeGL() override
    {
        initializeOpenGLFunctions();

        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);

        // Generate a checkerboard pattern for the texture
        QImage textureImage(1024, 1024, QImage::Format_ARGB32);
        for (int y = 0; y < textureImage.height(); ++y)
        {
            for (int x = 0; x < textureImage.width(); ++x)
            {
                int c = (((x & 0x20) == 0) ^ ((y & 0x20)  == 0)) * 255;
                textureImage.setPixel(x, y, qRgb(c, c, c));
            }
        }

        glEnable(GL_TEXTURE_2D);

        // Load the texture into OpenGL
        m_texture = new QOpenGLTexture(textureImage);
        m_texture->setMinificationFilter(QOpenGLTexture::Nearest);
        m_texture->setMagnificationFilter(QOpenGLTexture::Linear);
        m_texture->setWrapMode(QOpenGLTexture::Repeat);
    }

    void paintGL() override
    {
        glClear(GL_COLOR_BUFFER_BIT);

        // Draw the quad with the texture
        m_texture->bind();
        glBegin(GL_QUADS);
        glTexCoord2f(0.0f, 0.0f);
        glVertex2f(-1.0f, -1.0f);
        glTexCoord2f(1.0f, 0.0f);
        glVertex2f(1.0f, -1.0f);
        glTexCoord2f(1.0f, 1.0f);
        glVertex2f(1.0f, 1.0f);
        glTexCoord2f(0.0f, 1.0f);
        glVertex2f(-1.0f, 1.0);
        glEnd();
    }

    QOpenGLTexture *m_texture = nullptr;
};

int main(int argc, char **argv)
{
    QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts, true);
    QApplication app(argc, argv);

    MyGLWidget w_old;
    w_old.show();
    w_old.setWindowTitle("Old");

    while (true) {
        auto w = new MyGLWidget;
        w->setAttribute(Qt::WA_DeleteOnClose, true);
        w->show();
        QObject::connect(w, &QObject::destroyed, [] { QCoreApplication::quit(); });
        app.exec();
    }
}
```
</details>

This is curious as the QOpenGLWidget documentation on [Resource Initialization and Cleanup](https://doc.qt.io/qt-5/qopenglwidget.html#resource-initialization-and-cleanup) actually says:

> Proper cleanup is especially important due to context sharing. Even though each QOpenGLWidget's associated context is destroyed together with the QOpenGLWidget, the sharable resources in that context, like textures, will stay valid until the top-level window, in which the QOpenGLWidget lived, is destroyed. Additionally, settings like [Qt::AA_ShareOpenGLContexts](https://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum) and some Qt modules may trigger an even wider scope for sharing contexts, potentially leading to keeping the resources in question alive for the entire lifetime of the application. Therefore the safest and most robust is always to perform explicit cleanup for all resources and resource wrappers used in the QOpenGLWidget.

I provide this information just for completeness because I opened this issue - I have as stated earlier fixed my unit tests to clean up GL resources explicitly rather than depending on the resources being cleaned up when the GL context is closed. That was always sloppy and as can be seen for the Qt documentation quote not something that we could even rely on working.

**Comment by dcommander** [comment]
Are you saying that you still see the issue even with the fix I pushed yesterday? Which version of Qt are you using?

**Comment by tsondergaard** [comment]
Yes, I am still seeing the issue with the updated repro example that calls `QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts, true);` before creating the QApplication object.

**Comment by dcommander** [comment]
Which issue?  The GPU memory leak or the crash you mentioned in https://github.com/VirtualGL/virtualgl/issues/218#issuecomment-1354706318?

Which version of Qt are you using?

**Comment by dcommander** [comment]
Sorry.  For some reason, I missed https://github.com/VirtualGL/virtualgl/issues/218#issuecomment-1356278734, so I understand now what you're saying.

**Comment by dcommander** [comment]
With `AA_ShareOpenGLContexts` set, the following sequence of operations occurs (this is based on a VGL trace log from the start of the example program until after the first window is closed and re-opened):

- Create unshared context CTX1.
- Create window WIN1.
- Create context CTX2 shared with CTX1.
- Create context CTX3 shared with CTX2.
- Create Pbuffer PB1.
- Make current PB1, CTX3.
- Load texture TEX1.
- Create window WIN2.
- Create context CTX4 shared with CTX1.
- Create context CTX5 shared with CTX4.
- Create Pbuffer PB2.
- Make current PB2, CTX5.
- Load texture TEX2.
- Make current PB1, CTX3.
- Make current WIN1, CTX2.
- Swap buffers WIN1.
- Swap buffers WIN1.
- Make current PB2, CTX5.
- Make current WIN2, CTX4.
- Swap buffers WIN2.
- Swap buffers WIN2.
- *** **Close window** ***
- Make current PB2, CTX5.
- Make current 0, 0.
- Destroy CTX5.
- Destroy PB2.
- Make current WIN2, CTX4.
- Make current 0, 0.
- Destroy CTX4.
- Destroy WIN2.
- Create window WIN3.
- Create context CTX6 shared with CTX1.
- Create context CTX7 shared with CTX6.
- Create Pbuffer PB3.
- Make current PB3, CTX7.
- Load texture TEX3.
- Make current WIN3, CTX6.
- Swap buffers WIN3.
- Swap buffers WIN3.

TEX2, which is loaded into CTX5, is the source of the leak.  CTX5 is shared indirectly with CTX1, which survives after the window is closed.  CTX3 is also shared indirectly with CTX1, and both of those contexts survive after the window is closed. Thus, I echo your confusion regarding why the program doesn't leak with the GLX back end or without VGL.  Perhaps, because CTX1 is unshared, CTX3 and CTX5 share objects with CTX1 but not with each other, i.e. context sharing is not distributive.  However, I can find no documentation to support that assertion.  The scant documentation I could find on the subject says that there is no "primary" OpenGL context, i.e. no one context owns the data being shared.  That would imply that OpenGL context sharing is distributive, which would invalidate my hypothesis.

Regardless, even with the modifications I made because of this issue, the EGL back end still shares all contexts with the RBO context behind the scenes, and the RBO context's lifespan is the union of the lifespans of all contexts and fake Pbuffers that are created with it.  Thus, there will still be situations in which OpenGL objects survive longer with the EGL back end than they would with the GLX back end or without VGL.  I just don't understand why this is one of those situations.

**Comment by tsondergaard** [comment]
I have no idea. I have asked in https://cpplang.slack.com/archives/C29936TQC/p1671630094674359 if Qt is doing something special with OpenGL context sharing.
